from selenium.webdriver.common.by import By

class MainPageLocators():
    # header
    LOGO_PIC = (By.CSS_SELECTOR, "body > div.brace.grid-base > header > div.header__body.grid-base > div.header__slim > div > div.header-slim-section__logo > div > a > img")
    ON_AIR = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(1) > a > span")
    TOKYO_2020 = (By.CSS_SELECTOR, "div.header__slim > div > div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(2) > a > span")
    TVGUIDE = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(3) > a > span")
    LIVE = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(4) > a > span")
    NEWS = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(5) > a > span")
    MATCHPREMIER = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(6) > a > span")
    VIDEO = (By.CSS_SELECTOR, "div.header__body.grid-base > div.header__slim > div > div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(7) > a")
    SUBSCRIPTIONS = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li:nth-child(8) > a > span")
    MATCH_APP = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(1) > a > span")
    CHANNEL_STRANA = (By.CSS_SELECTOR, "div.header-slim-section__basic.ab-menu > div > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(2) > a > span")
    # types_of_sports
    FOOTBALL = (By.CSS_SELECTOR, "div > div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(1) > a > span")
    HOCKEY = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(2) > a > span")
    BOXING = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(3) > a > span")
    BASKETBALL = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(4) > a > span")
    FORMULA_1 = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(5) > a > span")
    FIGURE_SKATING = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(6) > a > span")
    BIATHLON = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(7) > a > span")
    SKIING = (By.CSS_SELECTOR, "div.header-main-section__basic > div > div.header-basic-section__nav > nav > ul > li:nth-child(8) > a > span")
    KORONAVIRUS = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(1) > a > span")
    CYBER = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(2) > a > span")
    SUMMER = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(3) > a > span")
    WINTER = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(4) > a > span")
    AUTOSPORT = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(5) > a > span")
    ATHLETICS = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(6) > a > span")
    VOLLEYBALL = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(7) > a > span")
    CHESS = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(8) > a > span")
    TENNIS = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(9) > a > span")
    ATHLETES = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(10) > a > span")
    TOURS_3D = (By.CSS_SELECTOR, "div.header-basic-section__nav > nav > ul > li.navlist__item.flexible-navigation__dropdown > div > ul > li:nth-child(11) > a > span")
    N_AIR = (By.CSS_SELECTOR, "div.header-main-section__live > div > div.live-preview__item.live-preview__item_contains_button > a > div > span.live-preview__link-title")